services:
    pgsql:
        image: postgis/postgis:15-3.4
        restart: always
        shm_size: 128mb
        # volumes:
        #     - type: tmpfs
        #       target: /dev/shm
        #       tmpfs:
        #         size: 134217728 # 128*2^20 bytes = 128Mb
        ports:
            - "7778:5432"
        networks:
            - temmulex-dev-network
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: temmulex
            
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - temmulex-dev-network

    redis:
        image: redis:latest
        user: redis
        networks:
            - temmulex-dev-network
        ports:
            - "7779:6379"

networks:
    temmulex-dev-network:
        driver: bridge
